using ThabeSoft.Mediator.SourceGenerator.Models;

namespace ThabeSoft.Mediator.SourceGenerator.Services.Builders;


/// <summary>
/// 代码文件构建器
/// </summary>
public interface ICodeFileBuilder
{
    string FileName { get; }
    string Build(IReadOnlyCollection<ITypeInfo> typeInfos);
}

/// <summary>
/// 代码文件构建
/// </summary>
public abstract class CodeFileBuilderBase(string fileName, string @namespace) : ICodeFileBuilder
{
    protected const string NewLine = "\r\n";


    private readonly List<string> _using_namespaces = [];

    public string FileName { get;  } = fileName;
    public string Namesapce { get; private set; } = @namespace;
    public IReadOnlyList<string> UsingNamespace => _using_namespaces;


    /// <summary>
    /// 添加名字空间
    /// </summary>
    protected void AddUsingNamespace(string @namespace)
    {
        _using_namespaces.Add(@namespace);
    }
    /// <summary>
    /// 设置名字空间
    /// </summary>
    protected void SetNamespace(string @namespace)
    {
        Namesapce = @namespace;
    }


    // 生成内容
    protected abstract string BuildContentStatements(IReadOnlyCollection<ITypeInfo> typeTnfos);


    /// <summary>
    /// 构建代码, 如果没有生成返回 <see cref="string.Empty"/>
    /// </summary>
    public virtual string Build(IReadOnlyCollection<ITypeInfo> typeTnfos)
    {
        var content_code = BuildContentStatements(typeTnfos);
        if (string.IsNullOrWhiteSpace(content_code)) return string.Empty;

        var header_code = BuildFileHeadStatements(DateTime.Now);
        var using_code = BuildUsingStatements(_using_namespaces);


        return $$"""
{{header_code}}

{{using_code}}

namespace {{Namesapce}}
{
{{content_code}}
}
""";
    }


    /// <summary>
    /// 生成文件头代码
    /// </summary>
    /// <returns></returns>
    protected virtual string BuildFileHeadStatements(DateTime generateTime)
    {
        return $"""
// <auto-generated />
// 
// Time: {generateTime:yyyy-MM-dd HH:mm:ss}
//
#pragma warning disable CS1591      // 缺少 XML 注释
#pragma warning disable CS8669      // 成员上的特性将隐藏继承的成员
#pragma warning disable CS0436      // 类型冲突
""";
    }

    /// <summary>
    /// 从名字空间构建 Using 代码
    /// </summary>
    /// <param name="namespaces"></param>
    /// <returns></returns>
    protected virtual string BuildUsingStatements(IEnumerable<string> namespaces)
    {
        var using_codes = namespaces
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => $"using {x.Trim()};")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(x => x);

        return string.Join(NewLine, using_codes);
    }
}
