<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>ThabeSoft.Mediator</RootNamespace>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>

	<!--包信息-->
	<PropertyGroup>

		<!--生成-->
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<!--基础-->
		<PackageId>ThabeSoft.Mediator.Contracts</PackageId>
		<Version>0.1.0-alpha.1</Version>
		<Title>ThabeSoft.Mediator.Contracts</Title>

		<!--描述-->
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>中介者协议，包含 IRequest、INotification</Description>
		<PackageTags>mediator;cqs;abstractions;中介者</PackageTags>

	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

</Project>
