<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<!--包信息-->
	<PropertyGroup>

		<!--生成-->
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<!--基础-->
		<PackageId>ThabeSoft.Mediator</PackageId>
		<Version>0.1.0-alpha.2</Version>
		<Title>ThabeSoft.Mediator</Title>

		<!--描述-->
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>一个基于源生成器的中介者实现</Description>
		<PackageTags>mediator;cqs;abstractions;中介者</PackageTags>

	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.8" />
	</ItemGroup>

	<!--嵌入源生成器-->
	<ItemGroup>
		<None Include="..\ThabeSoft.Mediator.SourceGenerator\bin\$(Configuration)\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.0/cs" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ThabeSoft.Mediator.Abstractions\ThabeSoft.Mediator.Abstractions.csproj" />
	</ItemGroup>

</Project>
