<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		

		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
	</PropertyGroup>

	<!--包信息-->
	<PropertyGroup>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<!-- 基础信息 -->
		<Company>ThabeSoft</Company>
		<Product>Mediator</Product>
		<Version>0.1.7</Version>

		<!-- NuGet 包信息 -->
		<Title>ThabeSoft.Mediator</Title>
		<Description>一个基于源生成器的中介者模式实现</Description>
		<Authors>DaThabe</Authors>
		<PackageTags>mediator;cqs;abstractions;source-generator</PackageTags>

		<!-- 链接 -->
		<PackageProjectUrl>https://github.com/thabesoft/ThabeSoft.Mediator</PackageProjectUrl>
		<RepositoryUrl>https://github.com/thabesoft/ThabeSoft.Mediator</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<!-- 法律 -->
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Copyright>Copyright © ThabeSoft 2026</Copyright>

		<!-- 文档 -->
		<!--<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>-->

		<!-- 调试 -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<!-- 分析器 -->
		
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="11.0.0-preview.3.26207.106" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\ThabeSoft.Mediator.SourceGenerator\bin\$(Configuration)\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/roslyn4.0/cs" Visible="false" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\ThabeSoft.Mediator.Abstractions\ThabeSoft.Mediator.Abstractions.csproj" />
	</ItemGroup>

</Project>
