//using Microsoft.CodeAnalysis;
//using System.Xml.Linq;
//using ThabeSoft.Mediator.SourceGenerator.Extensions;
//using ThabeSoft.Mediator.SourceGenerator.Models;

//namespace ThabeSoft.Mediator.SourceGenerator.Builders;



///// <summary>
///// 代码文件构建
///// </summary>
//public abstract class CodeFileBuilderBase(string fileName, string @namespace)
//{
    


//    private readonly List<string> _using_namespaces = [];

//    public string FileName { get;  } = fileName;
//    public string Namesapce { get; private set; } = @namespace;
//    public IReadOnlyList<string> UsingNamespace => _using_namespaces;


//    /// <summary>
//    /// 添加名字空间
//    /// </summary>
//    protected void AddUsingNamespace(string @namespace)
//    {
//        _using_namespaces.Add(@namespace);
//    }
//    /// <summary>
//    /// 设置名字空间
//    /// </summary>
//    protected void SetNamespace(string @namespace)
//    {
//        Namesapce = @namespace;
//    }


//    // 生成内容
//    protected abstract string BuildContentStatements(IReadOnlyCollection<TypeRegistration> infos);


//    /// <summary>
//    /// 构建代码, 如果没有生成返回 <see cref="string.Empty"/>
//    /// </summary>
//    public virtual void Build(SourceProductionContext context, IReadOnlyCollection<TypeRegistration> infos)
//    {
//        var content_code = BuildContentStatements(infos);
//        if (string.IsNullOrWhiteSpace(content_code)) return;

//        var header_code = BuildFileHeadStatements(DateTime.Now);
//        var using_code = BuildUsingStatements(_using_namespaces);

//        var content = BuildFile(header_code, using_code, content_code);

//        context.AddSource(FileName, content);
//    }

//    /// <summary>
//    /// 生成文件
//    /// </summary>
//    /// <param name="header_code"></param>
//    /// <param name="using_code"></param>
//    /// <param name="content_code"></param>
//    /// <returns></returns>
//    protected virtual string BuildFile(string header_code, string using_code, string content_code)
//    {
//        return $$"""
//{{header_code}}

//{{using_code}}

//namespace {{Namesapce}}
//{
//{{content_code}}
//}
//""";
//    }

//    /// <summary>
//    /// 生成文件头代码
//    /// </summary>
//    /// <returns></returns>
//    protected virtual string BuildFileHeadStatements(DateTime generateTime)
//    {
//        return $"""
//// <auto-generated />
//// 
//// Time: {generateTime:yyyy-MM-dd HH:mm:ss}
////
//#pragma warning disable CS1591      // 缺少 XML 注释
//#pragma warning disable CS8669      // 成员上的特性将隐藏继承的成员
//#pragma warning disable CS0436      // 类型冲突
//""";
//    }

//    /// <summary>
//    /// 从名字空间构建 Using 代码
//    /// </summary>
//    /// <param name="namespaces"></param>
//    /// <returns></returns>
//    protected virtual string BuildUsingStatements(IEnumerable<string> namespaces)
//    {
//        var using_codes = namespaces
//            .Where(x => !string.IsNullOrWhiteSpace(x))
//            .Select(x => $"using {x.Trim()};")
//            .Distinct(StringComparer.Ordinal)
//            .OrderBy(x => x);

//        return string.Join(TypeBuildExtensions.NewLine, using_codes);
//    }
//}
