namespace ThabeSoft.Mediator.SourceGenerator.Builders;

/// <summary>
/// 代码构建基类
/// </summary>
internal abstract class CodeFileBuilderBase(string @namespace)
{
    protected const string NewLine = "\r\n";

    private string _namespace = @namespace;
    private readonly List<string> _namespaces = [];


    /// <summary>
    /// 添加名字空间
    /// </summary>
    /// <param name="namespace"></param>
    protected void AddUsingNamespace(string @namespace)
    {
        _namespaces.Add(@namespace);
    }
    /// <summary>
    /// 设置名字空间
    /// </summary>
    /// <param name="namespace"></param>
    protected void SetNamespace(string @namespace)
    {
        _namespace = @namespace;
    }


    // 生成内容
    protected abstract string BuildContentStatements();


    /// <summary>
    /// 构建代码, 如果没有生成返回 <see cref="string.Empty"/>
    /// </summary>
    /// <param name="generatorName"></param>
    /// <returns></returns>
    public virtual string Build()
    {
        var content_code = BuildContentStatements();
        if (string.IsNullOrWhiteSpace(content_code)) return string.Empty;

        var header_code = BuildFileHeadStatements(DateTime.Now);
        var using_code = BuildUsingStatements(_namespaces);


        return $$"""
{{header_code}}

{{using_code}}

namespace {{_namespace}}
{
{{content_code}}
}
""";
    }


    /// <summary>
    /// 生成文件头代码
    /// </summary>
    /// <returns></returns>
    protected virtual string BuildFileHeadStatements(DateTime generateTime)
    {
        return $"""
// <auto-generated />
// 
// Time: {generateTime:yyyy-MM-dd HH:mm:ss}
// 
// 此文件由源码生成器自动生成，请勿手动修改
// 如需修改配置，请使用 AddMediatorHandlers 的委托参数
//
#pragma warning disable CS1591      // 缺少 XML 注释
#pragma warning disable CS8669      // 成员上的特性将隐藏继承的成员
#pragma warning disable CS0436      // 类型冲突
""";
    }

    /// <summary>
    /// 从名字空间构建 Using 代码
    /// </summary>
    /// <param name="namespaces"></param>
    /// <returns></returns>
    protected virtual string BuildUsingStatements(IEnumerable<string> namespaces)
    {
        var using_codes = namespaces
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => $"using {x.Trim()};")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(x => x);

        return string.Join(NewLine, using_codes);
    }
}
