<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BenchmarkDotNet" Version="0.15.8" />
		<PackageReference Include="Concordia.Core" Version="2.5.0" />
		<PackageReference Include="Concordia.Generator" Version="2.5.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="DispatchR.Mediator" Version="2.2.0" />
		<PackageReference Include="MediatR" Version="14.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Src\ThabeSoft.Mediator\ThabeSoft.Mediator.csproj" />
		<ProjectReference Include="..\..\Src\ThabeSoft.Mediator.SourceGenerator\ThabeSoft.Mediator.SourceGenerator.csproj" ReferenceOutputAssembly="false" OutputItemType="Analyzer" />
	</ItemGroup>

</Project>
