<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;netstandard2.1</TargetFrameworks>
		<RootNamespace>ThabeSoft.Mediator</RootNamespace>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<!--包信息-->
	<PropertyGroup>

		<!--生成-->
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>

		<!--基础-->
		<PackageId>ThabeSoft.Mediator.Abstractions</PackageId>
		<Version>0.1.0-alpha.1</Version>
		<Title>ThabeSoft.Mediator</Title>

		<!--描述-->
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<Description>中介者模式的抽象接口定义，包含 IRequestHandler、INotificationHandler、IRequestPipelineBehavior 等</Description>
		<PackageTags>mediator;cqs;abstractions;中介者</PackageTags>

	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<!-- 为不原生支持 ValueTask 的框架引入 NuGet 包 -->
	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' ">
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ThabeSoft.Mediator.Contracts\ThabeSoft.Mediator.Contracts.csproj" />
	</ItemGroup>

</Project>
