<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>ThabeSoft.Mediator</RootNamespace>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

	<!--包信息-->
	<PropertyGroup>
		<!-- 基础信息 -->
		<Company>ThabeSoft</Company>
		<Product>ThabeSoft.Mediator</Product>
		<Version>1.0.0</Version>

		<!-- NuGet 包信息 -->
		<Title>ThabeSoft.Mediator.Abstractions</Title>
		<Description>中介者模式的抽象接口定义，包含 IRequest、IRequestHandler、INotification 等核心接口。</Description>
		<Authors>DaThabe</Authors>
		<PackageTags>mediator;cqs;abstractions;source-generator</PackageTags>

		<!-- 链接 -->
		<PackageProjectUrl>https://github.com/thabesoft/ThabeSoft.Mediator</PackageProjectUrl>
		<RepositoryUrl>https://github.com/thabesoft/ThabeSoft.Mediator</RepositoryUrl>
		<RepositoryType>git</RepositoryType>

		<!-- 法律 -->
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<Copyright>Copyright © ThabeSoft 2026</Copyright>

		<!-- 文档 -->
		<!--<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>icon.png</PackageIcon>-->

		<!-- 调试 -->
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>

		<!-- 兼容性 -->
		<TargetFrameworks>netstandard2.0;net8.0;net10.0</TargetFrameworks>
		<LangVersion>latest</LangVersion>
		<Nullable>enable</Nullable>

		<!-- 分析器 -->
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
	</PropertyGroup>

	<!-- 为不原生支持 ValueTask 的框架引入 NuGet 包 -->
	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' ">
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\ThabeSoft.Mediator.Contracts\ThabeSoft.Mediator.Contracts.csproj" />
	</ItemGroup>

</Project>
