<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<RootNamespace>ThabeSoft.Mediator</RootNamespace>
		<LangVersion>preview</LangVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	</PropertyGroup>

	<!--包信息-->
	<PropertyGroup>
		<Company>ThabeSoft</Company>
		<Product>Mediator</Product>
		<Version>0.1.0</Version>
	</PropertyGroup>

	<!-- 为不原生支持 ValueTask 的框架引入 NuGet 包 -->
	<ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0' ">
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.6.3" />
	</ItemGroup>
	
	<ItemGroup>
	  <ProjectReference Include="..\..\ThabeSoft.Mediator.Contracts\ThabeSoft.Mediator.Contracts.csproj" />
	</ItemGroup>

</Project>
