namespace ThabeSoft.Mediator.SourceGenerator.Codes;


internal static class GeneratorHelper
{
    /// <summary>
    /// 从名字空间构建 Using 代码
    /// </summary>
    /// <param name="namespaces"></param>
    /// <returns></returns>
    public static string GenerateUsingCode(IEnumerable<string> namespaces)
    {
        return string.Join("\n", namespaces.Select(x => $"using {x};"));
    }


    /// <summary>
    /// 生成文件头
    /// </summary>
    /// <returns></returns>
    public static string GenerateFileHead()
    {
        return $"""
// <auto-generated />
// 
// ThabeSoft.Mediator.SourceGenerator
// Time: {DateTime.Now:yyyy-MM-dd HH:mm:ss}
// 
// 此文件由源码生成器自动生成，请勿手动修改
// 如需修改配置，请使用 AddMediatorHandlers 的委托参数
//
#pragma warning disable CS1591      // 缺少 XML 注释
#pragma warning disable CS8669      // 成员上的特性将隐藏继承的成员
#pragma warning disable CS0436      // 类型冲突
""";
    }
}
