using Microsoft.CodeAnalysis;

namespace ThabeSoft.Mediator.SourceGenerator.Extensions;

public static class TypeBuildExtensions
{
    public static string NewLine { get; } = "\r\n";

    /// <summary>
    /// 不包含泛型的全名称, 如 global::ThabeSoft.Mediator.IRequesthandler
    /// </summary>
    public static SymbolDisplayFormat GlobalNonGenericFullName { get; } = new
    (
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.None
    );

    /// <summary>
    /// 全名, 如 global::ThabeSoft.Mediator.SourceGenerator.Extensions.TypeParserExtensiosn
    /// </summary>
    public static SymbolDisplayFormat GlobalFullName { get; } = new
    (
        globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Included,
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces
    );

    /// <summary>
    /// 全名, 如 ThabeSoft.Mediator.SourceGenerator.Extensions.TypeParserExtensiosn
    /// </summary>
    public static SymbolDisplayFormat NonGenericFullName { get; } = new
    (
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
        genericsOptions: SymbolDisplayGenericsOptions.None
    );



    /// <summary>
    /// 获取特性信息
    /// </summary>
    /// <param name="classSymbol"></param>
    /// <param name="attributeFullName"></param>
    /// <returns></returns>
    public static AttributeData? GetAttributeData(this INamedTypeSymbol classSymbol, string attributeFullName)
    {
        foreach (var att in classSymbol.GetAttributes())
        {
            var att_full_name = att.AttributeClass?.ToDisplayString();
            if (att_full_name == attributeFullName) return att;
        }

        return null;
    }

    /// <summary>
    /// 使用空间构建Using语句
    /// </summary>
    public static string BuildUsingText(IEnumerable<string> namespaces)
    {
        var using_codes = namespaces
            .Where(x => !string.IsNullOrWhiteSpace(x))
            .Select(x => $"using {x.Trim()};")
            .Distinct(StringComparer.Ordinal)
            .OrderBy(x => x);

        return string.Join(NewLine, using_codes);
    }

    /// <summary>
    /// 构建文件头
    /// </summary>
    public static string BuildFileHeadText(DateTime generateTime)
    {
        return $"""
// <auto-generated />
// 
// Time: {generateTime:yyyy-MM-dd HH:mm:ss}
//
#pragma warning disable CS1591      // 缺少 XML 注释
#pragma warning disable CS8669      // 成员上的特性将隐藏继承的成员
#pragma warning disable CS0436      // 类型冲突
""";
    }

    /// <summary>
    /// 用默认模板构建
    /// </summary>
    public static string BuildDefaultTemplate(DateTime generateTime, IEnumerable<string> usingNamespaces, string @namespace, string content)
    {
        return $$"""
{{BuildFileHeadText(generateTime)}}

{{BuildUsingText(usingNamespaces)}}

namespace {{@namespace}}
{
{{content}}
}
""";
    }
    /// <summary>
    /// 用默认模板构建
    /// </summary>
    public static string BuildDefaultTemplate(IEnumerable<string> usingNamespaces, string @namespace, string content)
    {
        return BuildDefaultTemplate(DateTime.Now, usingNamespaces, @namespace, content);
    }
}